apiVersion: v1
kind: Secret
metadata:
  name: queue-app
  labels:
    {{- include "postgres-job-queue.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ printf "postgres://%s:%s@postgres:%v/%s?sslmode=disable" .Values.postgres.auth.user .Values.postgres.auth.password .Values.postgres.service.port .Values.postgres.auth.database | quote }}
