apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    {{- include "postgres-job-queue.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "postgres-job-queue.postgresSelectorLabels" . | nindent 4 }}
  ports:
    - name: postgres
      port: {{ .Values.postgres.service.port }}
      targetPort: postgres
