apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  labels:
    {{- include "postgres-job-queue.labels" . | nindent 4 }}
spec:
  serviceName: postgres-headless
  replicas: 1
  selector:
    matchLabels:
      {{- include "postgres-job-queue.postgresSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "postgres-job-queue.labels" . | nindent 8 }}
        {{- include "postgres-job-queue.postgresSelectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: postgres
          image: {{ printf "%s:%s" .Values.postgres.image.repository .Values.postgres.image.tag | quote }}
          imagePullPolicy: {{ .Values.postgres.image.pullPolicy }}
          ports:
            - name: postgres
              containerPort: {{ .Values.postgres.service.port }}
          envFrom:
            - secretRef:
                name: postgres
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - psql -U "$POSTGRES_USER" -d "$POSTGRES_DB" -c "select 1"
            initialDelaySeconds: 5
            periodSeconds: 5
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
        labels:
          {{- include "postgres-job-queue.labels" . | nindent 10 }}
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.postgres.persistence.size | quote }}
